//Post
export const STUDENT_POST_REQUEST = "STUDENT_POST_REQUEST "
export const STUDENT_POST_SUCCESS = "STUDENT_POST_SUCCESS"
export const STUDENT_POST_FAIL = "STUDENT_POST_FAIL"

//Get
export const STUDENT_GET_REQUEST = "STUDENT_GET_REQUEST "
export const STUDENT_GET_SUCCESS = "STUDENT_GET_SUCCESS"
export const STUDENT_GET_FAIL = "STUDENT_GET_FAIL"

//delete
export const STUDENT_DELETE_REQUEST = "STUDENT_DELETE_REQUEST "
export const STUDENT_DELETE_SUCCESS = "STUDENT_DELETE_SUCCESS"
export const STUDENT_DELETE_FAIL = "STUDENT_DELETE_FAIL"